const crypto = require('crypto');

/**
 * Helper to generate random alphabetic string
 */
function randomAlpha(length) {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  let res = '';
  const bytes = crypto.randomBytes(length);
  for (let i = 0; i < length; i++) {
    res += chars[bytes[i] % chars.length];
  }
  return res;
}

/**
 * Helper to generate random numeric string
 */
function randomDigits(length) {
  const digits = '0123456789';
  let res = '';
  const bytes = crypto.randomBytes(length);
  for (let i = 0; i < length; i++) {
    res += digits[bytes[i] % digits.length];
  }
  return res;
}

/**
 * Generate meeting credentials and URL based on provider
 *
 * @param {Object} params
 * @param {'google_meet'|'zoom'|'jitsi'|'custom'} params.provider
 * @param {string} [params.title]
 * @param {string} [params.tenantId]
 * @param {string} [params.itemId]
 * @returns {Promise<{ provider: string, joinUrl: string, meetingId: string, passcode?: string, autoGenerated: boolean }>}
 */
async function generateMeetingDetails({
  provider = 'jitsi',
  title = '',
  tenantId = 'workspace',
  itemId = '',
}) {
  const cleanTenant = (tenantId || 'workspace')
    .replace(/[^a-zA-Z0-9]/g, '')
    .toLowerCase()
    .slice(0, 8);

  const cleanTitle = (title || '')
    .replace(/[^a-zA-Z0-9]/g, '')
    .toLowerCase()
    .slice(0, 10);

  const uniqueSuffix = itemId
    ? String(itemId).slice(-6)
    : crypto.randomBytes(3).toString('hex');

  switch (provider) {
    case 'google_meet': {
      // Google Meet code format: xxx-yyyy-zzz (3 lowercase letters - 4 lowercase letters - 3 lowercase letters)
      const part1 = randomAlpha(3);
      const part2 = randomAlpha(4);
      const part3 = randomAlpha(3);
      const meetingId = `${part1}-${part2}-${part3}`;
      const joinUrl = `https://meet.google.com/${meetingId}`;

      return {
        provider: 'google_meet',
        joinUrl,
        meetingId,
        passcode: '',
        autoGenerated: true,
      };
    }

    case 'jitsi':
    default: {
      const roomSlug = [cleanTenant, cleanTitle, uniqueSuffix]
        .filter(Boolean)
        .join('-');
      const roomName = `saby-${roomSlug || 'meet'}`;
      const joinUrl = `https://meet.jit.si/${roomName}`;

      return {
        provider: 'jitsi',
        joinUrl,
        meetingId: roomName,
        passcode: '',
        autoGenerated: true,
      };
    }
  }
}

module.exports = {
  generateMeetingDetails,
};
