const mongoose = require('mongoose');
const httpStatus = require('http-status');
const { WorkItem, User, Role, ProjectForm, TenantOnboarding, GlobalSettings } = require('../models');
const ApiError = require('../utils/ApiError');
const reminderTriggerService = require('./reminderTrigger.service');
const videoMeetingService = require('./videoMeeting.service');

const resolveFormAttachment = async (formAttachment, user) => {
  if (!formAttachment || !formAttachment.enabled) {
    return formAttachment ? { ...formAttachment, enabled: false } : undefined;
  }
  const projectId = formAttachment.projectId || formAttachment.formId;
  if (!projectId) return formAttachment;

  const foundForm = await ProjectForm.findOne({
    tenantId: user.tenantId,
    deletedAt: null,
    $or: [{ projectId }, { formId: projectId }],
  }).select('projectId formId title publicRef shareRef');

  const publicRef =
    formAttachment.publicRef || foundForm?.publicRef || undefined;
  const shareRef = formAttachment.shareRef || foundForm?.shareRef || undefined;
  const title = formAttachment.title || foundForm?.title || 'Attached Form';
  const url =
    formAttachment.url ||
    (shareRef || publicRef || foundForm?.projectId
      ? `/s/${shareRef || publicRef || foundForm.projectId}`
      : undefined);

  return {
    enabled: true,
    projectId: foundForm?.projectId || formAttachment.projectId,
    formId: foundForm?.formId || formAttachment.formId || undefined,
    title,
    publicRef,
    shareRef,
    url,
    includeBarcode: formAttachment.includeBarcode !== false,
  };
};

const resolveMeeting = async (meeting, tenantId, itemId = '', title = '') => {
  if (!meeting || !meeting.enabled) {
    return meeting ? { ...meeting, enabled: false } : undefined;
  }
  let { joinUrl, meetingId, passcode } = meeting;
  let autoGenerated = Boolean(meeting.autoGenerated);

  // If joinUrl is missing or autoGenerated is true, auto-generate via videoMeetingService
  if (!joinUrl || autoGenerated) {
    const generated = await videoMeetingService.generateMeetingDetails({
      provider: meeting.provider || 'jitsi',
      title,
      tenantId,
      itemId,
    });
    joinUrl = generated.joinUrl;
    meetingId = meetingId || generated.meetingId;
    passcode = passcode || generated.passcode;
    autoGenerated = true;
  }

  return {
    enabled: true,
    provider: meeting.provider || 'jitsi',
    joinUrl: joinUrl || '',
    meetingId: meetingId || undefined,
    passcode: passcode || undefined,
    autoGenerated,
  };
};

const generateAiAgenda = ({
  title = '',
  description = '',
  type = 'event',
  startAt,
  endAt,
  meeting,
  formAttachment,
  agendaTopics,
  targetedOutcomes,
}) => {
  const durationMinutes =
    startAt && endAt
      ? Math.max(
          15,
          Math.round(
            (new Date(endAt).getTime() - new Date(startAt).getTime()) / 60000
          )
        )
      : 60;

  const topics = [];
  if (Array.isArray(agendaTopics) && agendaTopics.length > 0) {
    agendaTopics.forEach((t) => {
      if (t && String(t).trim()) topics.push(String(t).trim());
    });
  } else if (typeof agendaTopics === 'string' && agendaTopics.trim()) {
    agendaTopics
      .split(/[\n;]+/)
      .map((t) => t.trim())
      .filter(Boolean)
      .forEach((t) => topics.push(t));
  } else {
    const rawTags = (description || '')
      .split(/[\n,•;]+/)
      .map((t) => t.trim())
      .filter(Boolean);

    if (rawTags.length > 0) {
      rawTags.forEach((tag) => {
        const cleanTag = tag.replace(/^[^a-zA-Z0-9]+/, '');
        if (cleanTag) {
          topics.push(`${cleanTag} — Strategic alignment & execution block`);
        }
      });
    } else {
      topics.push(`Executive Briefing & Key Objectives for ${title}`);
      topics.push(`Operational Workflow Review & Action Items`);
      topics.push(`Q&A, Open Discussion, and Next Milestones`);
    }
  }

  let objectives = [];
  if (Array.isArray(targetedOutcomes) && targetedOutcomes.length > 0) {
    targetedOutcomes.forEach((o) => {
      if (o && String(o).trim()) objectives.push(String(o).trim());
    });
  } else if (typeof targetedOutcomes === 'string' && targetedOutcomes.trim()) {
    targetedOutcomes
      .split(/[\n;]+/)
      .map((o) => o.trim())
      .filter(Boolean)
      .forEach((o) => objectives.push(o));
  } else {
    objectives = [
      `Establish complete organizational alignment on objectives for "${title}".`,
      `Review deliverables, milestones, and assigned operational roles.`,
      ...(formAttachment
        ? [
            `Collect and verify required data submissions for "${
              formAttachment.title || 'Attached Form'
            }" via live data capture.`,
          ]
        : []),
      `Agree on follow-up responsibilities, action checkpoints, and deadlines.`,
    ];
  }

  const preparationNotes = meeting?.enabled
    ? [
        `Please join the ${
          meeting.provider === 'google_meet' ? 'Google Meet' : 'Jitsi Meet'
        } conference 2-3 minutes early to test your connection.`,
        'Prepare your questions and project notes beforehand.',
      ]
    : [
        'Review current workspace milestones and bring relevant updates to the session.',
      ];

  const summary = `AI-synthesized operational agenda for "${title}" (${durationMinutes} mins). Designed to ensure clear accountability, focused alignment, and high-impact execution.`;

  const formattedMarkdown = `### Overview\n${summary}\n\n### Key Agenda Topics\n${topics
    .map((t, i) => `${i + 1}. **${t}**`)
    .join('\n')}\n\n### Session Objectives\n${objectives
    .map((o) => `* ${o}`)
    .join('\n')}\n\n### Participant Preparation\n${
    Array.isArray(preparationNotes)
      ? preparationNotes.map((p) => `* ${p}`).join('\n')
      : preparationNotes
  }`;

  return {
    summary,
    topics,
    objectives,
    preparationNotes,
    formattedMarkdown,
    generatedAt: new Date(),
  };
};

const resolveAssignees = async (assignees, user) => {
  if (!assignees) return undefined;

  const userIds = [
    ...new Set(
      assignees
        .filter((assignee) => assignee.kind === 'user' && assignee.userId)
        .map((assignee) => assignee.userId)
    ),
  ];
  const roleIds = [
    ...new Set(
      assignees
        .filter((assignee) => assignee.kind === 'role' && assignee.roleId)
        .map((assignee) => assignee.roleId)
    ),
  ];
  const formProjectIds = [
    ...new Set(
      assignees
        .filter(
          (assignee) =>
            assignee.kind === 'form_submissions' && assignee.projectId
        )
        .map((assignee) => assignee.projectId)
    ),
  ];

  const [users, roles, forms] = await Promise.all([
    userIds.length > 0
      ? User.find({
          tenantId: user.tenantId,
          deletedAt: null,
          $or: [{ _id: { $in: userIds } }, { userId: { $in: userIds } }],
        }).select('_id userId firstname lastname email phoneNumber')
      : [],
    roleIds.length > 0
      ? Role.find({
          tenantId: user.tenantId,
          _id: { $in: roleIds },
        }).select('_id name')
      : [],
    formProjectIds.length > 0
      ? ProjectForm.find({
          tenantId: user.tenantId,
          deletedAt: null,
          $or: [
            { projectId: { $in: formProjectIds } },
            { formId: { $in: formProjectIds } },
          ],
        }).select('_id projectId formId title publicRef shareRef')
      : [],
  ]);

  const usersById = new Map();
  users.forEach((member) => {
    const resolved = {
      kind: 'user',
      userId: String(member._id),
      name: [member.firstname, member.lastname].filter(Boolean).join(' '),
      email: member.email || undefined,
      phone: member.phoneNumber || undefined,
    };
    usersById.set(String(member._id), resolved);
    if (member.userId) usersById.set(String(member.userId), resolved);
  });

  const rolesById = new Map();
  roles.forEach((r) => {
    rolesById.set(String(r._id), r);
  });

  if (userIds.some((userId) => !usersById.has(userId))) {
    throw new ApiError(
      httpStatus.BAD_REQUEST,
      'One or more assignees are not active members of this tenant'
    );
  }
  if (roleIds.some((roleId) => !rolesById.has(roleId))) {
    throw new ApiError(
      httpStatus.BAD_REQUEST,
      'One or more assigned roles do not exist for this tenant'
    );
  }

  return assignees.map((assignee) => {
    if (assignee.kind === 'all') {
      return {
        kind: 'all',
        name: assignee.name || '@all (All Users)',
      };
    }
    if (assignee.kind === 'role') {
      const foundRole = rolesById.get(String(assignee.roleId));
      const baseName = foundRole ? foundRole.name : assignee.name || 'Role';
      return {
        kind: 'role',
        roleId: String(assignee.roleId),
        name: baseName.startsWith('Role:') ? baseName : `Role: ${baseName}`,
      };
    }
    if (assignee.kind === 'form_submissions') {
      const foundForm = forms.find(
        (f) =>
          f.projectId === assignee.projectId ||
          f.formId === assignee.projectId ||
          String(f._id) === assignee.projectId
      );
      const baseTitle =
        foundForm?.title ||
        foundForm?.identity?.title ||
        assignee.name ||
        'Form';
      return {
        kind: 'form_submissions',
        projectId: foundForm ? foundForm.projectId : assignee.projectId,
        formId: foundForm?.formId || assignee.formId || undefined,
        name: String(baseTitle).startsWith('Form:')
          ? baseTitle
          : `Form: ${baseTitle}`,
      };
    }
    if (assignee.kind === 'contact') {
      return {
        kind: 'contact',
        name: assignee.name,
        email: assignee.email || undefined,
        phone: assignee.phone || undefined,
      };
    }
    return usersById.get(assignee.userId);
  });
};

const createWorkItem = async (body, user) => {
  if (body.idempotencyKey) {
    const existingItem = await WorkItem.findOne({
      tenantId: user.tenantId,
      idempotencyKey: body.idempotencyKey,
    });
    if (existingItem) {
      return existingItem;
    }
  }

  const {
    reminder,
    formAttachment,
    meeting,
    aiAgenda: customAiAgenda,
    agendaTopics,
    targetedOutcomes,
    ...workItemBody
  } = body;

  const resolvedAttachment = formAttachment
    ? await resolveFormAttachment(formAttachment, user)
    : undefined;
  const resolvedMeeting = meeting
    ? await resolveMeeting(meeting, user.tenantId, '', workItemBody.title)
    : undefined;

  let aiAgenda = customAiAgenda;
  if (!aiAgenda || !aiAgenda.topics || aiAgenda.topics.length === 0) {
    aiAgenda = generateAiAgenda({
      title: workItemBody.title,
      description: workItemBody.description,
      type: workItemBody.type,
      startAt: workItemBody.startAt,
      endAt: workItemBody.endAt,
      meeting: resolvedMeeting,
      formAttachment: resolvedAttachment,
      agendaTopics,
      targetedOutcomes,
    });
  }

  // Generate unique shareCode
  let shareCode = WorkItem.generateShareCode();
  while (await WorkItem.exists({ shareCode })) {
    shareCode = WorkItem.generateShareCode();
  }

  let item;
  try {
    item = await WorkItem.create({
      ...workItemBody,
      idempotencyKey: body.idempotencyKey || undefined,
      shareCode,
      ...(resolvedAttachment !== undefined
        ? { formAttachment: resolvedAttachment }
        : {}),
      ...(resolvedMeeting !== undefined ? { meeting: resolvedMeeting } : {}),
      ...(workItemBody.assignees
        ? { assignees: await resolveAssignees(workItemBody.assignees, user) }
        : {}),
      aiAgenda,
      tenantId: user.tenantId,
      createdBy: String(user.id || user._id),
    });
  } catch (err) {
    if (err && err.code === 11000 && body.idempotencyKey) {
      const existing = await WorkItem.findOne({
        tenantId: user.tenantId,
        idempotencyKey: body.idempotencyKey,
      });
      if (existing) return existing;
    }
    throw err;
  }

  if (reminder) {
    let scheduledAt = reminder.scheduledAt;
    if (!scheduledAt && reminder.minutesBefore && workItemBody.startAt) {
      scheduledAt = new Date(
        new Date(workItemBody.startAt).getTime() -
          Number(reminder.minutesBefore) * 60 * 1000
      );
    }
    if (scheduledAt && new Date(scheduledAt) > new Date()) {
      try {
        await reminderTriggerService.createReminderTrigger(
          {
            entityType: 'work-item',
            entityId: String(item._id),
            scheduledAt,
            timezone: reminder.timezone || 'UTC',
            recurrence: reminder.recurrence || { frequency: 'none' },
            channels:
              reminder.channels && reminder.channels.length > 0
                ? reminder.channels
                : ['email'],
            recipients: item.assignees,
          },
          user
        );
      } catch (err) {
        console.error('Failed to schedule reminder trigger:', err.message);
      }
    }
  }
  return item;
};

const resolveAssigneeEmails = async (emails = [], user) => {
  const normalizedEmails = emails.map((email) => email.trim().toLowerCase());
  if (new Set(normalizedEmails).size !== normalizedEmails.length) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Duplicate assignee email');
  }
  if (!normalizedEmails.length) return [];

  const members = await User.find({
    tenantId: user.tenantId,
    deletedAt: null,
    status: true,
    email: { $in: normalizedEmails },
  }).select('_id firstname lastname email phoneNumber');
  const membersByEmail = new Map(
    members.map((member) => [
      member.email.toLowerCase(),
      {
        kind: 'user',
        userId: String(member._id),
        name: [member.firstname, member.lastname].filter(Boolean).join(' '),
        email: member.email,
        phone: member.phoneNumber || undefined,
      },
    ])
  );

  return normalizedEmails.map(
    (email) =>
      membersByEmail.get(email) || {
        kind: 'contact',
        name: email,
        email,
      }
  );
};

const importWorkItems = async (items, user) => {
  const results = [];
  const errors = [];

  for (let i = 0; i < items.length; i += 1) {
    const raw = items[i];
    try {
      // Normalize form attachment
      let formAttachment = raw.formAttachment;
      const projectFormId = raw.projectFormId || raw.project_form_id;
      if (!formAttachment && (projectFormId || raw.attachForm || raw.attach_form)) {
        formAttachment = {
          enabled: true,
          projectId: projectFormId || undefined,
          formId: projectFormId || undefined,
          includeBarcode:
            raw.includeBarcode !== false && raw.include_barcode !== false,
        };
      }

      // Normalize video meeting
      let meeting = raw.meeting;
      const isVideo =
        raw.enableVideoConference === true ||
        raw.enable_video_conference === true ||
        Boolean(
          raw.meetingUrl ||
            raw.meeting_url ||
            raw.meetingProvider ||
            raw.meeting_provider
        );
      if (!meeting && isVideo) {
        meeting = {
          enabled: true,
          provider: raw.meetingProvider || raw.meeting_provider || 'jitsi',
          joinUrl: raw.meetingUrl || raw.meeting_url || undefined,
        };
      }

      // Normalize reminder
      let reminder = raw.reminder;
      const reminderMinutes = raw.reminderMinutes || raw.reminder_minutes;
      if (!reminder && reminderMinutes) {
        reminder = {
          minutesBefore: Number(reminderMinutes),
        };
      }

      // Normalize assignees
      let assignees = raw.assignees;
      if (!assignees) {
        const assigneeEmails =
          raw.assigneeEmails || raw.assignee_emails || [];
        const notificationContacts =
          raw.notificationContacts || raw.notification_contacts || [];
        const userAssignees = await resolveAssigneeEmails(assigneeEmails, user);
        assignees = [
          ...userAssignees,
          ...notificationContacts.map((contact) => ({
            kind: 'contact',
            name: contact.name || contact.email,
            email: contact.email || undefined,
            phone: contact.phone || undefined,
          })),
        ];
      }

      const itemPayload = {
        type: raw.type || 'event',
        title: raw.title,
        description: raw.description || '',
        startAt: raw.startAt || raw.start_at,
        endAt: raw.endAt || raw.end_at,
        allDay: Boolean(raw.allDay || raw.all_day),
        status: raw.status || 'scheduled',
        priority: raw.priority || undefined,
        assignees,
        formAttachment,
        meeting,
        reminder,
        agendaTopics: raw.agendaTopics || raw.agenda_topics,
        targetedOutcomes: raw.targetedOutcomes || raw.targeted_outcomes,
        aiAgenda: raw.aiAgenda,
        idempotencyKey: raw.idempotencyKey || raw.idempotency_key,
      };

      const createdItem = await createWorkItem(itemPayload, user);
      results.push(createdItem);
    } catch (err) {
      errors.push({
        row: i + 1,
        title: raw.title || `Row ${i + 1}`,
        error: err.message || 'Failed to import row',
      });
    }
  }

  return { results, errors };
};

const queryWorkItems = ({ from, to, type, status }, user) => {
  const filter = { tenantId: user.tenantId };
  if (type) filter.type = type;
  if (status) filter.status = status;
  if (from || to) {
    filter.startAt = {};
    if (from) filter.startAt.$lte = new Date(to || from);
    if (to) filter.endAt = { $gte: new Date(from || to) };
  }
  return WorkItem.find(filter).sort({ startAt: 1 });
};

const updateWorkItem = async (id, body, user) => {
  const item = await WorkItem.findOne({ _id: id, tenantId: user.tenantId });
  if (!item) throw new ApiError(httpStatus.NOT_FOUND, 'Work item not found');
  const { assignees, formAttachment, meeting, ...updates } = body;
  Object.assign(item, updates);
  if (assignees !== undefined)
    item.assignees = await resolveAssignees(assignees, user);
  if (formAttachment !== undefined) {
    item.formAttachment = await resolveFormAttachment(formAttachment, user);
  }
  if (meeting !== undefined) {
    item.meeting = await resolveMeeting(
      meeting,
      user.tenantId,
      id,
      item.title
    );
  }
  await item.save();
  if (['completed', 'cancelled'].includes(item.status)) {
    await reminderTriggerService.suppressEntityReminders({
      entityType: 'work-item',
      entityId: item._id,
      tenantId: user.tenantId,
    });
  }
  return item;
};

const getWorkItem = async (id, user) => {
  const item = await WorkItem.findOne({ _id: id, tenantId: user.tenantId });
  if (!item) throw new ApiError(httpStatus.NOT_FOUND, 'Work item not found');
  return item;
};

const deleteWorkItem = async (id, user) => {
  const item = await WorkItem.findOneAndDelete({
    _id: id,
    tenantId: user.tenantId,
  });
  if (!item) throw new ApiError(httpStatus.NOT_FOUND, 'Work item not found');
};

const generateMeeting = async ({ provider, title }, user) => {
  return videoMeetingService.generateMeetingDetails({
    provider,
    title,
    tenantId: user?.tenantId,
  });
};

const getPublicWorkItem = async (reference) => {
  const isMongoId = mongoose.Types.ObjectId.isValid(reference);
  const query = isMongoId
    ? { $or: [{ _id: reference }, { shareCode: reference }] }
    : { shareCode: reference };

  const item = await WorkItem.findOne(query);
  if (!item) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Event or task not found');
  }

  // Ensure legacy records have a shareCode assigned
  if (!item.shareCode) {
    let code = WorkItem.generateShareCode();
    while (await WorkItem.exists({ shareCode: code })) {
      code = WorkItem.generateShareCode();
    }
    item.shareCode = code;
    await WorkItem.updateOne({ _id: item._id }, { $set: { shareCode: code } }).catch(() => null);
  }

  let aiAgenda = item.aiAgenda
    ? item.aiAgenda.toObject
      ? item.aiAgenda.toObject()
      : { ...item.aiAgenda }
    : null;

  if (!aiAgenda || !aiAgenda.summary) {
    aiAgenda = generateAiAgenda({
      title: item.title,
      description: item.description,
      type: item.type,
      startAt: item.startAt,
      endAt: item.endAt,
      meeting: item.meeting,
      formAttachment: item.formAttachment,
    });
  }

  // Defensively ensure preparationNotes, topics, objectives are arrays
  if (aiAgenda) {
    if (typeof aiAgenda.preparationNotes === 'string') {
      aiAgenda.preparationNotes = [aiAgenda.preparationNotes];
    } else if (!Array.isArray(aiAgenda.preparationNotes)) {
      aiAgenda.preparationNotes = [];
    }
    if (typeof aiAgenda.topics === 'string') {
      aiAgenda.topics = [aiAgenda.topics];
    } else if (!Array.isArray(aiAgenda.topics)) {
      aiAgenda.topics = [];
    }
    if (typeof aiAgenda.objectives === 'string') {
      aiAgenda.objectives = [aiAgenda.objectives];
    } else if (!Array.isArray(aiAgenda.objectives)) {
      aiAgenda.objectives = [];
    }
    if (typeof aiAgenda.nextSteps === 'string') {
      aiAgenda.nextSteps = [aiAgenda.nextSteps];
    } else if (!Array.isArray(aiAgenda.nextSteps)) {
      aiAgenda.nextSteps = [];
    }

    // Provide default structured agenda topics only if none exist
    if (aiAgenda.topics.length === 0) {
      aiAgenda.topics = [
        'Context, Background & Project Alignment',
        'Operational Milestones & Metrics Review',
        'Key Architecture Decisions & Technical Specs',
        'Blockers, Constraints & Resource Allocation',
        'Deliverables, Action Checkpoints & Deadlines',
      ];
    }
  }

  // Resolve Tenant / Organization branding & contact details
  let tenant = {
    name: 'Saby Workspace',
    email: '',
    phone: '',
    address: '',
    city: '',
    state: '',
    country: '',
    website: '',
    logoUrl: '',
  };

  if (item.tenantId) {
    const [onboarding, globalSettings] = await Promise.all([
      TenantOnboarding.findOne({ tenantId: item.tenantId }).lean().catch(() => null),
      GlobalSettings.findOne({ tenantId: item.tenantId }).lean().catch(() => null),
    ]);

    if (onboarding?.company) {
      if (onboarding.company.name) tenant.name = onboarding.company.name;
      if (onboarding.company.email) tenant.email = onboarding.company.email;
      if (onboarding.company.phone) tenant.phone = onboarding.company.phone;

      // Construct a clean, human-friendly address
      const addrComponents = [];
      if (onboarding.company.address && onboarding.company.address.trim().length > 2) {
        addrComponents.push(onboarding.company.address.trim());
      }
      if (onboarding.company.city) addrComponents.push(onboarding.company.city.trim());
      if (onboarding.company.state) addrComponents.push(onboarding.company.state.trim());
      if (onboarding.company.country) addrComponents.push(onboarding.company.country.trim());

      if (addrComponents.length > 0) {
        tenant.address = addrComponents.join(', ');
      }
    }

    if (globalSettings) {
      if (
        (!tenant.name || tenant.name === 'Saby Workspace' || tenant.name === 'Default Organization Name') &&
        globalSettings.organizationName &&
        globalSettings.organizationName !== 'Default Organization Name'
      ) {
        tenant.name = globalSettings.organizationName;
      }
      if (!tenant.email && globalSettings.contactEmail) tenant.email = globalSettings.contactEmail;
      if (!tenant.phone && globalSettings.contactPhone) tenant.phone = globalSettings.contactPhone;
      if (globalSettings.websiteUrl) tenant.website = globalSettings.websiteUrl;
      if (globalSettings.logoUrl) tenant.logoUrl = globalSettings.logoUrl;
    }
  }

  // Fallback to organizer user if email is still missing
  if (!tenant.email && item.createdBy) {
    const organizer = await User.findById(item.createdBy).select('firstname lastname email phoneNumber').lean().catch(() => null);
    if (organizer) {
      if (!tenant.email && organizer.email) tenant.email = organizer.email;
      if (!tenant.phone && organizer.phoneNumber) tenant.phone = organizer.phoneNumber;
      if (!tenant.name || tenant.name === 'Saby Workspace') {
        const orgName = `${organizer.firstname || ''} ${organizer.lastname || ''}`.trim();
        if (orgName) tenant.name = orgName;
      }
    }
  }

  // Resolve resources
  const resources = [];
  if (Array.isArray(item.resources) && item.resources.length > 0) {
    resources.push(
      ...item.resources.map((r) => ({
        id: String(r._id || ''),
        title: r.title,
        url: r.url,
        type: r.type || 'url',
        storageFileId: r.storageFileId || null,
        description: r.description || '',
      }))
    );
  }

  // If form attachment is enabled and not already present
  if (item.formAttachment?.enabled && item.formAttachment?.url) {
    const hasForm = resources.some(
      (r) => r.type === 'form' || r.url === item.formAttachment.url
    );
    if (!hasForm) {
      resources.push({
        id: 'resource-form',
        title: item.formAttachment.title || 'Data Capture Form',
        url: item.formAttachment.url,
        type: 'form',
        description: 'Online submission form',
      });
    }
  }

  // If meeting is enabled and not already present
  if (item.meeting?.enabled && item.meeting?.joinUrl) {
    const hasMeeting = resources.some(
      (r) => r.type === 'meeting' || r.url === item.meeting.joinUrl
    );
    if (!hasMeeting) {
      resources.push({
        id: 'resource-meeting',
        title:
          item.meeting.provider === 'google_meet'
            ? 'Google Meet Room'
            : 'Video Conference',
        url: item.meeting.joinUrl,
        type: 'meeting',
        description: 'Live interactive room',
      });
    }
  }

  // Default suggested resources if none configured yet
  if (resources.length === 0) {
    resources.push(
      {
        id: 'default-kanban',
        title: 'Kanban Board',
        url: '#kanban',
        type: 'kanban',
        description: 'Sprint & operational tasks',
      },
      {
        id: 'default-doc',
        title: 'Documentation',
        url: '#docs',
        type: 'doc',
        description: 'Project brief & guidelines',
      },
      {
        id: 'default-design',
        title: 'Design File',
        url: '#design',
        type: 'design',
        description: 'Figma specs & design tokens',
      }
    );
  }

  return {
    id: String(item._id),
    tenantId: item.tenantId || null,
    createdBy: item.createdBy || null,
    shareCode: item.shareCode || null,
    shortUrl: item.shareCode ? `/a/${item.shareCode}` : `/agenda/${item._id}`,
    title: item.title,
    type: item.type,
    description: item.description,
    startAt: item.startAt,
    endAt: item.endAt,
    allDay: item.allDay,
    status: item.status,
    priority: item.priority,
    assignees: item.assignees || [],
    resources,
    tenant,
    meeting: item.meeting?.enabled ? item.meeting : null,
    formAttachment: item.formAttachment?.enabled ? item.formAttachment : null,
    aiAgenda,
    createdAt: item.createdAt,
  };
};

const addPublicResource = async (reference, resourceBody) => {
  const isId = mongoose.Types.ObjectId.isValid(reference);
  const filter = isId
    ? { $or: [{ _id: reference }, { shareCode: reference }] }
    : { shareCode: reference };

  const item = await WorkItem.findOne(filter);
  if (!item) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Agenda item not found');
  }

  if (!Array.isArray(item.resources)) {
    item.resources = [];
  }

  const newResource = {
    title: resourceBody.title,
    url: resourceBody.url,
    type: resourceBody.type || 'url',
    storageFileId: resourceBody.storageFileId || undefined,
    description: resourceBody.description || undefined,
  };

  item.resources.push(newResource);
  await item.save();

  return item.resources;
};

module.exports = {
  createWorkItem,
  importWorkItems,
  queryWorkItems,
  getWorkItem,
  getPublicWorkItem,
  addPublicResource,
  updateWorkItem,
  deleteWorkItem,
  generateMeeting,
  generateAiAgenda,
  resolveFormAttachment,
  resolveMeeting,
};
