const mongoose = require('mongoose');
const { customAlphabet } = require('nanoid');
const { toJSON, paginate } = require('./plugins');

const shareCodeAlphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const generateShortCode = customAlphabet(shareCodeAlphabet, 7);

const assigneeSchema = new mongoose.Schema(
  {
    kind: {
      type: String,
      enum: ['user', 'contact', 'all', 'role', 'form_submissions'],
      default: 'user',
    },
    userId: { type: String },
    roleId: { type: String },
    projectId: { type: String },
    formId: { type: String },
    name: { type: String, required: true, trim: true, default: '@all' },
    email: { type: String, trim: true, lowercase: true },
    phone: { type: String, trim: true },
  },
  { _id: false }
);

const formAttachmentSchema = new mongoose.Schema(
  {
    enabled: { type: Boolean, default: false },
    projectId: { type: String, trim: true },
    formId: { type: String, trim: true },
    title: { type: String, trim: true },
    publicRef: { type: String, trim: true },
    shareRef: { type: String, trim: true },
    url: { type: String, trim: true },
    includeBarcode: { type: Boolean, default: true },
  },
  { _id: false }
);

const meetingSchema = new mongoose.Schema(
  {
    enabled: { type: Boolean, default: false },
    provider: {
      type: String,
      enum: ['google_meet', 'jitsi', 'custom'],
      default: 'jitsi',
    },
    joinUrl: { type: String, trim: true },
    meetingId: { type: String, trim: true },
    passcode: { type: String, trim: true },
    autoGenerated: { type: Boolean, default: false },
  },
  { _id: false }
);

const aiAgendaSchema = new mongoose.Schema(
  {
    summary: { type: String, trim: true },
    topics: [{ type: String, trim: true }],
    objectives: [{ type: String, trim: true }],
    preparationNotes: { type: mongoose.Schema.Types.Mixed },
    nextSteps: [{ type: String, trim: true }],
    formattedMarkdown: { type: String, trim: true },
    generatedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const resourceSchema = new mongoose.Schema(
  {
    title: { type: String, trim: true, required: true },
    url: { type: String, trim: true, required: true },
    type: {
      type: String,
      enum: ['storage', 'url', 'form', 'meeting', 'doc', 'kanban', 'design'],
      default: 'url',
    },
    storageFileId: { type: String, trim: true },
    description: { type: String, trim: true },
  },
  { _id: true, timestamps: true }
);

const workItemSchema = mongoose.Schema(
  {
    tenantId: { type: String, required: true, index: true },
    createdBy: { type: String, required: true, index: true },
    type: {
      type: String,
      enum: ['event', 'task'],
      required: true,
      index: true,
    },
    title: { type: String, required: true, trim: true },
    description: { type: String, trim: true, default: '' },
    startAt: { type: Date, required: true, index: true },
    endAt: { type: Date, required: true },
    allDay: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ['scheduled', 'in-progress', 'completed', 'cancelled'],
      default: 'scheduled',
      index: true,
    },
    priority: { type: String, enum: ['low', 'medium', 'high'] },
    assignees: { type: [assigneeSchema], default: [] },
    resources: { type: [resourceSchema], default: [] },
    formAttachment: { type: formAttachmentSchema, default: undefined },
    shareCode: {
      type: String,
      unique: true,
      sparse: true,
      index: true,
      trim: true,
    },
    meeting: { type: meetingSchema, default: undefined },
    aiAgenda: { type: aiAgendaSchema, default: undefined },
    idempotencyKey: {
      type: String,
      sparse: true,
      index: true,
      trim: true,
    },
  },
  { timestamps: true }
);

workItemSchema.statics.generateShareCode = function () {
  return generateShortCode();
};

workItemSchema.index({ tenantId: 1, startAt: 1, endAt: 1 });
workItemSchema.index({ tenantId: 1, idempotencyKey: 1 }, { unique: true, sparse: true });
workItemSchema.plugin(toJSON);
workItemSchema.plugin(paginate);

module.exports = mongoose.model('WorkItem', workItemSchema);
